//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nou {
	
	
	public partial class home {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.PlaceHolder placeholder1;
		
		protected System.Web.UI.HtmlControls.HtmlForm addFile;
		
		protected System.Web.UI.WebControls.TextBox title;
		
		protected System.Web.UI.WebControls.TextBox type;
		
		protected System.Web.UI.WebControls.TextBox genre;
		
		protected System.Web.UI.WebControls.TextBox path;
		
		protected System.Web.UI.HtmlControls.HtmlForm deleteFile;
		
		protected System.Web.UI.WebControls.TextBox fileID;
		
		protected System.Web.UI.HtmlControls.HtmlForm editFile;
		
		protected System.Web.UI.WebControls.TextBox eid;
		
		protected System.Web.UI.WebControls.TextBox etitle;
		
		protected System.Web.UI.WebControls.TextBox etype;
		
		protected System.Web.UI.WebControls.TextBox egenre;
		
		protected System.Web.UI.WebControls.TextBox epath;
		
		protected System.Web.UI.HtmlControls.HtmlForm filterForm;
		
		protected System.Web.UI.WebControls.TextBox genreFilter;
		
		protected System.Web.UI.WebControls.PlaceHolder placeholder2;
		
		protected System.Web.UI.WebControls.FileUpload FileUpload1;
		
		protected System.Web.UI.WebControls.Label Label1;

		protected System.Web.UI.WebControls.FileUpload FileUpload2;


	}
}
